##PDS PRACTICAL 2

**NAME:VARAD VIJAY AMBEKAR**

**DIV: SY-A**

**ROLL NO.: A-02**

**Aim : Data Ingestion and Cleaning: Acquire data and prepare it for analysis.**

**Theory**

### 1. What is data ingestion and why is it important? Which Python library is used?

**Answer:**

Data ingestion is the process of collecting, importing, and loading data from various sources into a system where it can be stored, processed, and analyzed. These sources can include structured data (CSV files, databases), semi-structured data (JSON, XML), and unstructured data (logs, images).

In data science, data ingestion is the first and foundational step of the data pipeline. If this step is poorly handled, every subsequent step—cleaning, analysis, and modeling—will be flawed.

**Importance of Data Ingestion:**

*   Ensures data is available in a usable and structured format.
*   Integrates data from multiple sources into one system.
*   Maintains consistency and completeness of data.
*   Enables real-time or batch data processing.
*   Forms the base for accurate analysis and machine learning.

In Python, the most commonly used library for data ingestion and cleaning is Pandas. It provides powerful functions like:

*   `read_csv()` for CSV files
*   `read_excel()` for Excel files
*   `read_json()` for JSON data

**Example:**

```python
import pandas as pd
df = pd.read_csv("titanic.csv")
```



### 2. Why is data cleaning necessary?

**Answer:**

Data cleaning is the process of identifying and correcting errors, inconsistencies, and missing values in a dataset before performing analysis or applying machine learning algorithms.

Real-world data is rarely clean. It often contains:

*   Missing values (e.g., unknown age in Titanic dataset)
*   Duplicate records
*   Incorrect or inconsistent formats
*   Outliers or noise

If data is not cleaned:

*   Analysis results become inaccurate or misleading.
*   Machine learning models learn wrong patterns.
*   Predictions become unreliable.

**Benefits of Data Cleaning:**

*   Improves data quality and consistency.
*   Increases accuracy of analysis.
*   Enhances performance of machine learning models.
*   Reduces bias caused by incorrect data.

**Example (Titanic dataset):**
Missing values in the `Age` column must be handled:




### 3. How do you load a CSV file into a Pandas DataFrame?

**Answer:**

A CSV (Comma-Separated Values) file is one of the most common formats for storing tabular data. In Python, it can be loaded into a Pandas DataFrame using the `read_csv()` function.

This function reads the file and converts it into a structured format where:

*   Rows represent observations.
*   Columns represent features.

**Basic Syntax:**

```python
import pandas as pd
df = pd.read_csv("titanic.csv")
```

**Optional Parameters:**

*   `head()` → to preview data
*   `index_col` → to set index column
*   `na_values` → to define missing values

**Example:**

```python
df = pd.read_csv("titanic.csv")
df.head()
```



### 4. What is the difference between `head()` and `tail()`?

**Answer:**

Both `head()` and `tail()` functions are used to quickly inspect the dataset, but they differ in which part of the data they display.

| Function | Description                           |
| :------- | :------------------------------------ |
| `head()` | Displays the first few rows (default = 5) |
| `tail()` | Displays the last few rows (default = 5)  |

**Purpose:**

*   `head()` helps understand the structure and column names.
*   `tail()` helps verify the end of the dataset and detect anomalies.

**Example:**

```python
df.head()
df.tail()
```

You can also specify the number of rows:

```python
df.head(10)
df.tail(3)
```



### 5. How can you identify missing values in a dataset?

**Answer:**

Missing values are common in real-world datasets and must be identified before cleaning. In Pandas, missing values are typically represented as `NaN` (Not a Number).

You can detect missing values using the following methods:

**1. `isnull()` or `isna()`**

Returns a Boolean DataFrame indicating missing values.

```python
df.isnull()
```

**2. Count missing values using `sum()`**

```python
df.isnull().sum()
```

This shows how many missing values are present in each column.

**3. Check if any missing values exist**

```python
df.isnull().any()
```

**4. Visual inspection**

```python
df.info()
```

This shows non-null counts for each column.

**Example Insight (Titanic dataset):**

*   `Age` and `Cabin` columns often contain missing values.
*   These must be handled before analysis.

**1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
url = '/content/train (1).csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
age_column = df['Age']

age_column.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [ ]:
df['date'] = '14 Apr 1912'

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

In [ ]:
sorted_df = df.sort_values(by='Fare', ascending=False)

sorted_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14 Apr 1912
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,14 Apr 1912
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14 Apr 1912
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,14 Apr 1912
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,14 Apr 1912

In [ ]:
sorted_df = df.sort_values(by='Fare', ascending=False)

sorted_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14 Apr 1912
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,14 Apr 1912
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14 Apr 1912
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,14 Apr 1912
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,14 Apr 1912

In [ ]:
df_renamed = df.rename(columns={
    'Sex': 'Gender',
    'Pclass': 'Passenger_Class'
})

df_renamed.head()

,PassengerId,Survived,Passenger_Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
filtered_df = df[(df['Age'] > 30) & (df['Fare'] > 50)]

filtered_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,14 Apr 1912
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,14 Apr 1912
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,14 Apr 1912

In [ ]:

filtered_df = df[(df['Age'] > 30) & (df['Fare'] > 50)]

filtered_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,14 Apr 1912
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S,14 Apr 1912
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,14 Apr 1912

In [ ]:
grouped = df.groupby('Sex')['Fare'].mean()

grouped

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [ ]:
df2 = df[['PassengerId', 'Survived']]

merged_df = pd.merge(df, df2, on='PassengerId')

merged_df.head()

,PassengerId,Survived_x,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date,Survived_y
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912,0

In [ ]:
df_dropped = df.drop(columns=['Cabin'])

df_dropped_rows = df.dropna(subset=['Age'])

df_dropped.head()
df_dropped_rows.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,14 Apr 1912
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,14 Apr 1912
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,14 Apr 1912
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,14 Apr 1912
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,14 Apr 1912

In [ ]:

df.to_csv("processed_titanic.csv", index=False)

print("File saved successfully!")

File saved successfully!

**Conclusion**

This practical successfully demonstrated the fundamental steps of data ingestion, cleaning, and basic analysis using the Pandas library. Key operations such as loading data, handling missing values, filtering, sorting, and grouping were applied to prepare the dataset for further analysis. This exercise underscored the importance of data preprocessing in ensuring data quality and reliability, laying a solid foundation for more advanced data science tasks.